version: '4.0'

services:

  mssql:
    container_name: sql-server-personnal-config
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Novation96"
    ports:
      - 6433:1433