global using NotificationService.Repository;
global using NotificationService.Models;
global using NotificationService.Data;
global using NotificationService.Shared;
global using NotificationService.ExtensionMethods;
global using NotificationService.Services;
global using AutoMapper;
global using NotificationService.Dto;
global using NotificationService.Models.DataType;
